// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4IBD1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IBD2_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IBD3_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IBD4_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IBD5_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IBD6_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IBD7_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IBD8_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD2_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD3_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD4_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD5_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD6_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD7_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RCBD8_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4entrymean_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4IBD1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD1_mod, 0},
    {"_rcpp_module_boot_stan_fit4IBD2_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD2_mod, 0},
    {"_rcpp_module_boot_stan_fit4IBD3_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD3_mod, 0},
    {"_rcpp_module_boot_stan_fit4IBD4_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD4_mod, 0},
    {"_rcpp_module_boot_stan_fit4IBD5_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD5_mod, 0},
    {"_rcpp_module_boot_stan_fit4IBD6_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD6_mod, 0},
    {"_rcpp_module_boot_stan_fit4IBD7_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD7_mod, 0},
    {"_rcpp_module_boot_stan_fit4IBD8_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IBD8_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD1_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD2_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD2_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD3_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD3_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD4_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD4_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD5_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD5_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD6_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD6_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD7_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD7_mod, 0},
    {"_rcpp_module_boot_stan_fit4RCBD8_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RCBD8_mod, 0},
    {"_rcpp_module_boot_stan_fit4entrymean_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4entrymean_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProbBreed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
