// Generated by rstantools.  Do not edit by hand.

/*
    ProbBreed is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ProbBreed is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ProbBreed.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_RCBD5_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 61> locations_array__ =
  {" (found before start of program)",
  " (in 'RCBD5', line 16, column 4 to column 26)",
  " (in 'RCBD5', line 17, column 4 to column 24)",
  " (in 'RCBD5', line 18, column 4 to column 23)",
  " (in 'RCBD5', line 19, column 4 to column 12)",
  " (in 'RCBD5', line 20, column 4 to column 22)",
  " (in 'RCBD5', line 21, column 4 to column 17)",
  " (in 'RCBD5', line 22, column 4 to column 22)",
  " (in 'RCBD5', line 23, column 4 to column 17)",
  " (in 'RCBD5', line 24, column 4 to column 22)",
  " (in 'RCBD5', line 25, column 4 to column 17)",
  " (in 'RCBD5', line 26, column 4 to column 23)",
  " (in 'RCBD5', line 27, column 4 to column 18)",
  " (in 'RCBD5', line 28, column 4 to column 24)",
  " (in 'RCBD5', line 31, column 4 to column 26)",
  " (in 'RCBD5', line 51, column 4 to column 29)",
  " (in 'RCBD5', line 32, column 4 to column 50)",
  " (in 'RCBD5', line 53, column 6 to column 64)",
  " (in 'RCBD5', line 52, column 21 to line 54, column 7)",
  " (in 'RCBD5', line 52, column 6 to line 54, column 7)",
  " (in 'RCBD5', line 35, column 4 to column 29)",
  " (in 'RCBD5', line 36, column 4 to column 31)",
  " (in 'RCBD5', line 37, column 4 to column 26)",
  " (in 'RCBD5', line 38, column 4 to column 25)",
  " (in 'RCBD5', line 39, column 4 to column 25)",
  " (in 'RCBD5', line 40, column 4 to column 23)",
  " (in 'RCBD5', line 41, column 4 to column 25)",
  " (in 'RCBD5', line 42, column 4 to column 23)",
  " (in 'RCBD5', line 43, column 4 to column 25)",
  " (in 'RCBD5', line 44, column 4 to column 23)",
  " (in 'RCBD5', line 45, column 4 to column 26)",
  " (in 'RCBD5', line 46, column 4 to column 25)",
  " (in 'RCBD5', line 47, column 4 to column 35)",
  " (in 'RCBD5', line 48, column 4 to column 39)",
  " (in 'RCBD5', line 3, column 4 to column 19)",
  " (in 'RCBD5', line 4, column 4 to column 20)",
  " (in 'RCBD5', line 5, column 4 to column 20)",
  " (in 'RCBD5', line 6, column 4 to column 20)",
  " (in 'RCBD5', line 7, column 4 to column 20)",
  " (in 'RCBD5', line 8, column 11 to column 12)",
  " (in 'RCBD5', line 8, column 14 to column 16)",
  " (in 'RCBD5', line 8, column 4 to column 21)",
  " (in 'RCBD5', line 9, column 11 to column 12)",
  " (in 'RCBD5', line 9, column 14 to column 16)",
  " (in 'RCBD5', line 9, column 4 to column 21)",
  " (in 'RCBD5', line 10, column 11 to column 12)",
  " (in 'RCBD5', line 10, column 14 to column 16)",
  " (in 'RCBD5', line 10, column 4 to column 21)",
  " (in 'RCBD5', line 11, column 11 to column 12)",
  " (in 'RCBD5', line 11, column 14 to column 16)",
  " (in 'RCBD5', line 11, column 4 to column 21)",
  " (in 'RCBD5', line 12, column 10 to column 11)",
  " (in 'RCBD5', line 12, column 4 to column 20)",
  " (in 'RCBD5', line 13, column 4 to column 13)",
  " (in 'RCBD5', line 21, column 11 to column 13)",
  " (in 'RCBD5', line 23, column 11 to column 13)",
  " (in 'RCBD5', line 25, column 11 to column 13)",
  " (in 'RCBD5', line 27, column 11 to column 13)",
  " (in 'RCBD5', line 28, column 10 to column 11)",
  " (in 'RCBD5', line 31, column 11 to column 12)",
  " (in 'RCBD5', line 51, column 10 to column 11)"};
#include <stan_meta_header.hpp>
class model_RCBD5 final : public model_base_crtp<model_RCBD5> {
private:
  int n;
  int p1;
  int p3;
  int p4;
  int p5;
  Eigen::Matrix<double,-1,-1> Z1_data__;
  Eigen::Matrix<double,-1,-1> Z3_data__;
  Eigen::Matrix<double,-1,-1> Z4_data__;
  Eigen::Matrix<double,-1,-1> Z5_data__;
  std::vector<double> y;
  double phi;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z1{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z3{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z4{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z5{nullptr, 0, 0};
public:
  ~model_RCBD5() {}
  model_RCBD5(stan::io::var_context& context__, unsigned int
              random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_RCBD5_namespace::model_RCBD5";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 34;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 34;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "n", n, 1);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "p1", "int",
        std::vector<size_t>{});
      p1 = std::numeric_limits<int>::min();
      current_statement__ = 35;
      p1 = context__.vals_i("p1")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "p1", p1, 1);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "p3", "int",
        std::vector<size_t>{});
      p3 = std::numeric_limits<int>::min();
      current_statement__ = 36;
      p3 = context__.vals_i("p3")[(1 - 1)];
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "p3", p3, 1);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "p4", "int",
        std::vector<size_t>{});
      p4 = std::numeric_limits<int>::min();
      current_statement__ = 37;
      p4 = context__.vals_i("p4")[(1 - 1)];
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "p4", p4, 1);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "p5", "int",
        std::vector<size_t>{});
      p5 = std::numeric_limits<int>::min();
      current_statement__ = 38;
      p5 = context__.vals_i("p5")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "p5", p5, 1);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("Z1", "n", n);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("Z1", "p1", p1);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "Z1", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(p1)});
      Z1_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, p1,
                    std::numeric_limits<double>::quiet_NaN());
      new (&Z1) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z1_data__.data(), n,
        p1);
      {
        std::vector<local_scalar_t__> Z1_flat__;
        current_statement__ = 41;
        Z1_flat__ = context__.vals_r("Z1");
        current_statement__ = 41;
        pos__ = 1;
        current_statement__ = 41;
        for (int sym1__ = 1; sym1__ <= p1; ++sym1__) {
          current_statement__ = 41;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 41;
            stan::model::assign(Z1, Z1_flat__[(pos__ - 1)],
              "assigning variable Z1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 41;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 42;
      stan::math::validate_non_negative_index("Z3", "n", n);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("Z3", "p3", p3);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "Z3", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(p3)});
      Z3_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, p3,
                    std::numeric_limits<double>::quiet_NaN());
      new (&Z3) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z3_data__.data(), n,
        p3);
      {
        std::vector<local_scalar_t__> Z3_flat__;
        current_statement__ = 44;
        Z3_flat__ = context__.vals_r("Z3");
        current_statement__ = 44;
        pos__ = 1;
        current_statement__ = 44;
        for (int sym1__ = 1; sym1__ <= p3; ++sym1__) {
          current_statement__ = 44;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 44;
            stan::model::assign(Z3, Z3_flat__[(pos__ - 1)],
              "assigning variable Z3", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 44;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 45;
      stan::math::validate_non_negative_index("Z4", "n", n);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("Z4", "p4", p4);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "Z4", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(p4)});
      Z4_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, p4,
                    std::numeric_limits<double>::quiet_NaN());
      new (&Z4) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z4_data__.data(), n,
        p4);
      {
        std::vector<local_scalar_t__> Z4_flat__;
        current_statement__ = 47;
        Z4_flat__ = context__.vals_r("Z4");
        current_statement__ = 47;
        pos__ = 1;
        current_statement__ = 47;
        for (int sym1__ = 1; sym1__ <= p4; ++sym1__) {
          current_statement__ = 47;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 47;
            stan::model::assign(Z4, Z4_flat__[(pos__ - 1)],
              "assigning variable Z4", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 47;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 48;
      stan::math::validate_non_negative_index("Z5", "n", n);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("Z5", "p5", p5);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "Z5", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(p5)});
      Z5_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, p5,
                    std::numeric_limits<double>::quiet_NaN());
      new (&Z5) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z5_data__.data(), n,
        p5);
      {
        std::vector<local_scalar_t__> Z5_flat__;
        current_statement__ = 50;
        Z5_flat__ = context__.vals_r("Z5");
        current_statement__ = 50;
        pos__ = 1;
        current_statement__ = 50;
        for (int sym1__ = 1; sym1__ <= p5; ++sym1__) {
          current_statement__ = 50;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 50;
            stan::model::assign(Z5, Z5_flat__[(pos__ - 1)],
              "assigning variable Z5", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 50;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 51;
      stan::math::validate_non_negative_index("y", "n", n);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(n)});
      y = std::vector<double>(n, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 52;
      y = context__.vals_r("y");
      current_statement__ = 53;
      context__.validate_dims("data initialization", "phi", "double",
        std::vector<size_t>{});
      phi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 53;
      phi = context__.vals_r("phi")[(1 - 1)];
      current_statement__ = 54;
      stan::math::validate_non_negative_index("r", "p1", p1);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("g", "p3", p3);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("l", "p4", p4);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("gl", "p5", p5);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("y_gen", "n", n);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("expectation", "n", n);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("y_log_like", "n", n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + p1 + 1 + p3 + 1 + p4 + 1 + p5 + n;
  }
  inline std::string model_name() const final {
    return "model_RCBD5";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_RCBD5_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ s_sigma = DUMMY_VAR__;
      current_statement__ = 1;
      s_sigma = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ s_mu = DUMMY_VAR__;
      current_statement__ = 3;
      s_mu = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 4;
      mu = in__.template read<local_scalar_t__>();
      local_scalar_t__ s_r = DUMMY_VAR__;
      current_statement__ = 5;
      s_r = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> r =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p1, DUMMY_VAR__);
      current_statement__ = 6;
      r = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p1);
      local_scalar_t__ s_g = DUMMY_VAR__;
      current_statement__ = 7;
      s_g = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> g =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p3, DUMMY_VAR__);
      current_statement__ = 8;
      g = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p3);
      local_scalar_t__ s_l = DUMMY_VAR__;
      current_statement__ = 9;
      s_l = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> l =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p4, DUMMY_VAR__);
      current_statement__ = 10;
      l = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p4);
      local_scalar_t__ s_gl = DUMMY_VAR__;
      current_statement__ = 11;
      s_gl = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> gl =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p5, DUMMY_VAR__);
      current_statement__ = 12;
      gl = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p5);
      std::vector<local_scalar_t__> y_gen =
        std::vector<local_scalar_t__>(n, DUMMY_VAR__);
      current_statement__ = 13;
      y_gen = in__.template read<std::vector<local_scalar_t__>>(n);
      Eigen::Matrix<local_scalar_t__,-1,1> expectation =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
      current_statement__ = 16;
      stan::model::assign(expectation,
        stan::math::add(
          stan::math::add(
            stan::math::add(stan::math::add(mu, stan::math::multiply(Z1, r)),
              stan::math::multiply(Z3, g)), stan::math::multiply(Z4, l)),
          stan::math::multiply(Z5, gl)), "assigning variable expectation");
      {
        current_statement__ = 20;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(s_sigma, 0, phi));
        current_statement__ = 21;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma, 0, s_sigma));
        current_statement__ = 22;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(s_mu, 0, phi));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, 0, s_mu));
        current_statement__ = 24;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(s_r, 0, phi));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(r, 0, s_r));
        current_statement__ = 26;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(s_g, 0, phi));
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(g, 0, s_g));
        current_statement__ = 28;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(s_l, 0, phi));
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(l, 0, s_l));
        current_statement__ = 30;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(s_gl, 0, phi));
        current_statement__ = 31;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(gl, 0, s_gl));
        current_statement__ = 32;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y, expectation,
                         sigma));
        current_statement__ = 33;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y_gen, expectation,
                         sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_RCBD5_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double s_sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      s_sigma = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double s_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      s_mu = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      mu = in__.template read<local_scalar_t__>();
      double s_r = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      s_r = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,1> r =
        Eigen::Matrix<double,-1,1>::Constant(p1,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      r = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p1);
      double s_g = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      s_g = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,1> g =
        Eigen::Matrix<double,-1,1>::Constant(p3,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 8;
      g = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p3);
      double s_l = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      s_l = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,1> l =
        Eigen::Matrix<double,-1,1>::Constant(p4,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 10;
      l = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p4);
      double s_gl = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      s_gl = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      Eigen::Matrix<double,-1,1> gl =
        Eigen::Matrix<double,-1,1>::Constant(p5,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 12;
      gl = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p5);
      std::vector<double> y_gen =
        std::vector<double>(n, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 13;
      y_gen = in__.template read<std::vector<local_scalar_t__>>(n);
      Eigen::Matrix<double,-1,1> expectation =
        Eigen::Matrix<double,-1,1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(s_sigma);
      out__.write(sigma);
      out__.write(s_mu);
      out__.write(mu);
      out__.write(s_r);
      out__.write(r);
      out__.write(s_g);
      out__.write(g);
      out__.write(s_l);
      out__.write(l);
      out__.write(s_gl);
      out__.write(gl);
      out__.write(y_gen);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 16;
      stan::model::assign(expectation,
        stan::math::add(
          stan::math::add(
            stan::math::add(stan::math::add(mu, stan::math::multiply(Z1, r)),
              stan::math::multiply(Z3, g)), stan::math::multiply(Z4, l)),
          stan::math::multiply(Z5, gl)), "assigning variable expectation");
      if (emit_transformed_parameters__) {
        out__.write(expectation);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<double> y_log_like =
        std::vector<double>(n, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 19;
      for (int j = 1; j <= n; ++j) {
        current_statement__ = 17;
        stan::model::assign(y_log_like,
          stan::math::cauchy_lpdf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(j)),
            stan::model::rvalue(expectation, "expectation",
              stan::model::index_uni(j)), sigma),
          "assigning variable y_log_like", stan::model::index_uni(j));
      }
      out__.write(y_log_like);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ s_sigma = DUMMY_VAR__;
      current_statement__ = 1;
      s_sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_sigma);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
      local_scalar_t__ s_mu = DUMMY_VAR__;
      current_statement__ = 3;
      s_mu = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_mu);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 4;
      mu = in__.read<local_scalar_t__>();
      out__.write(mu);
      local_scalar_t__ s_r = DUMMY_VAR__;
      current_statement__ = 5;
      s_r = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_r);
      Eigen::Matrix<local_scalar_t__,-1,1> r =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p1, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(r,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p1),
        "assigning variable r");
      out__.write(r);
      local_scalar_t__ s_g = DUMMY_VAR__;
      current_statement__ = 7;
      s_g = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_g);
      Eigen::Matrix<local_scalar_t__,-1,1> g =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p3, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(g,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p3),
        "assigning variable g");
      out__.write(g);
      local_scalar_t__ s_l = DUMMY_VAR__;
      current_statement__ = 9;
      s_l = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_l);
      Eigen::Matrix<local_scalar_t__,-1,1> l =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p4, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(l,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p4),
        "assigning variable l");
      out__.write(l);
      local_scalar_t__ s_gl = DUMMY_VAR__;
      current_statement__ = 11;
      s_gl = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_gl);
      Eigen::Matrix<local_scalar_t__,-1,1> gl =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p5, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(gl,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p5),
        "assigning variable gl");
      out__.write(gl);
      std::vector<local_scalar_t__> y_gen =
        std::vector<local_scalar_t__>(n, DUMMY_VAR__);
      current_statement__ = 13;
      stan::model::assign(y_gen, in__.read<std::vector<local_scalar_t__>>(n),
        "assigning variable y_gen");
      out__.write(y_gen);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "s_sigma",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "s_mu", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "s_r", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "r", "double",
        std::vector<size_t>{static_cast<size_t>(p1)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "s_g", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "g", "double",
        std::vector<size_t>{static_cast<size_t>(p3)});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "s_l", "double",
        std::vector<size_t>{});
      current_statement__ = 10;
      context__.validate_dims("parameter initialization", "l", "double",
        std::vector<size_t>{static_cast<size_t>(p4)});
      current_statement__ = 11;
      context__.validate_dims("parameter initialization", "s_gl", "double",
        std::vector<size_t>{});
      current_statement__ = 12;
      context__.validate_dims("parameter initialization", "gl", "double",
        std::vector<size_t>{static_cast<size_t>(p5)});
      current_statement__ = 13;
      context__.validate_dims("parameter initialization", "y_gen", "double",
        std::vector<size_t>{static_cast<size_t>(n)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ s_sigma = DUMMY_VAR__;
      current_statement__ = 1;
      s_sigma = context__.vals_r("s_sigma")[(1 - 1)];
      out__.write_free_lb(0, s_sigma);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
      local_scalar_t__ s_mu = DUMMY_VAR__;
      current_statement__ = 3;
      s_mu = context__.vals_r("s_mu")[(1 - 1)];
      out__.write_free_lb(0, s_mu);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 4;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write(mu);
      local_scalar_t__ s_r = DUMMY_VAR__;
      current_statement__ = 5;
      s_r = context__.vals_r("s_r")[(1 - 1)];
      out__.write_free_lb(0, s_r);
      Eigen::Matrix<local_scalar_t__,-1,1> r =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p1, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> r_flat__;
        current_statement__ = 6;
        r_flat__ = context__.vals_r("r");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= p1; ++sym1__) {
          current_statement__ = 6;
          stan::model::assign(r, r_flat__[(pos__ - 1)],
            "assigning variable r", stan::model::index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(r);
      local_scalar_t__ s_g = DUMMY_VAR__;
      current_statement__ = 7;
      s_g = context__.vals_r("s_g")[(1 - 1)];
      out__.write_free_lb(0, s_g);
      Eigen::Matrix<local_scalar_t__,-1,1> g =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p3, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> g_flat__;
        current_statement__ = 8;
        g_flat__ = context__.vals_r("g");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= p3; ++sym1__) {
          current_statement__ = 8;
          stan::model::assign(g, g_flat__[(pos__ - 1)],
            "assigning variable g", stan::model::index_uni(sym1__));
          current_statement__ = 8;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(g);
      local_scalar_t__ s_l = DUMMY_VAR__;
      current_statement__ = 9;
      s_l = context__.vals_r("s_l")[(1 - 1)];
      out__.write_free_lb(0, s_l);
      Eigen::Matrix<local_scalar_t__,-1,1> l =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p4, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> l_flat__;
        current_statement__ = 10;
        l_flat__ = context__.vals_r("l");
        current_statement__ = 10;
        pos__ = 1;
        current_statement__ = 10;
        for (int sym1__ = 1; sym1__ <= p4; ++sym1__) {
          current_statement__ = 10;
          stan::model::assign(l, l_flat__[(pos__ - 1)],
            "assigning variable l", stan::model::index_uni(sym1__));
          current_statement__ = 10;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(l);
      local_scalar_t__ s_gl = DUMMY_VAR__;
      current_statement__ = 11;
      s_gl = context__.vals_r("s_gl")[(1 - 1)];
      out__.write_free_lb(0, s_gl);
      Eigen::Matrix<local_scalar_t__,-1,1> gl =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p5, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> gl_flat__;
        current_statement__ = 12;
        gl_flat__ = context__.vals_r("gl");
        current_statement__ = 12;
        pos__ = 1;
        current_statement__ = 12;
        for (int sym1__ = 1; sym1__ <= p5; ++sym1__) {
          current_statement__ = 12;
          stan::model::assign(gl, gl_flat__[(pos__ - 1)],
            "assigning variable gl", stan::model::index_uni(sym1__));
          current_statement__ = 12;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(gl);
      std::vector<local_scalar_t__> y_gen =
        std::vector<local_scalar_t__>(n, DUMMY_VAR__);
      current_statement__ = 13;
      y_gen = context__.vals_r("y_gen");
      out__.write(y_gen);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"s_sigma", "sigma", "s_mu", "mu",
                "s_r", "r", "s_g", "g", "s_l", "l", "s_gl", "gl", "y_gen"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"expectation"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"y_log_like"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(p1)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(p3)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(p4)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(p5)},
                std::vector<size_t>{static_cast<size_t>(n)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "s_sigma");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "s_mu");
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "s_r");
    for (int sym1__ = 1; sym1__ <= p1; ++sym1__) {
      param_names__.emplace_back(std::string() + "r" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_g");
    for (int sym1__ = 1; sym1__ <= p3; ++sym1__) {
      param_names__.emplace_back(std::string() + "g" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_l");
    for (int sym1__ = 1; sym1__ <= p4; ++sym1__) {
      param_names__.emplace_back(std::string() + "l" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_gl");
    for (int sym1__ = 1; sym1__ <= p5; ++sym1__) {
      param_names__.emplace_back(std::string() + "gl" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
      param_names__.emplace_back(std::string() + "y_gen" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "expectation" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_log_like" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "s_sigma");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "s_mu");
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "s_r");
    for (int sym1__ = 1; sym1__ <= p1; ++sym1__) {
      param_names__.emplace_back(std::string() + "r" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_g");
    for (int sym1__ = 1; sym1__ <= p3; ++sym1__) {
      param_names__.emplace_back(std::string() + "g" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_l");
    for (int sym1__ = 1; sym1__ <= p4; ++sym1__) {
      param_names__.emplace_back(std::string() + "l" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_gl");
    for (int sym1__ = 1; sym1__ <= p5; ++sym1__) {
      param_names__.emplace_back(std::string() + "gl" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
      param_names__.emplace_back(std::string() + "y_gen" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "expectation" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_log_like" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"s_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_r\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p1) + "},\"block\":\"parameters\"},{\"name\":\"s_g\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"g\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p3) + "},\"block\":\"parameters\"},{\"name\":\"s_l\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"l\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p4) + "},\"block\":\"parameters\"},{\"name\":\"s_gl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gl\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p5) + "},\"block\":\"parameters\"},{\"name\":\"y_gen\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"expectation\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_log_like\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"s_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_r\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p1) + "},\"block\":\"parameters\"},{\"name\":\"s_g\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"g\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p3) + "},\"block\":\"parameters\"},{\"name\":\"s_l\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"l\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p4) + "},\"block\":\"parameters\"},{\"name\":\"s_gl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gl\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p5) + "},\"block\":\"parameters\"},{\"name\":\"y_gen\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"expectation\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_log_like\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((((((1 + 1) + 1) + 1) + 1) + p1) + 1)
      + p3) + 1) + p4) + 1) + p5) + n);
    const size_t num_transformed = emit_transformed_parameters * (n);
    const size_t num_gen_quantities = emit_generated_quantities * (n);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((((((1 + 1) + 1) + 1) + 1) + p1) + 1)
      + p3) + 1) + p4) + 1) + p5) + n);
    const size_t num_transformed = emit_transformed_parameters * (n);
    const size_t num_gen_quantities = emit_generated_quantities * (n);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_RCBD5_namespace::model_RCBD5;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_RCBD5_namespace::profiles__;
}
#endif
#endif
